name: "Terraform"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to add comments to Pull Requests
  deployments: write # This is required to deactivate deployments


on:
  push:

  pull_request:

  workflow_dispatch:
    inputs:
      # [dev test ...]
      environment:
        description: environment to deploy to
        required: true
        type: string

jobs:
  terraform-plan-dev:
    uses: ./.github/workflows/tf-plan.yml
    secrets: inherit
    with:
      environment: dev
  apply-dev-approval:
    needs:
      - terraform-plan-dev
    runs-on: ubuntu-latest
    environment: dev-approval
    steps:
      - name: Approval gate for apply-dev
        run: |
          echo Approved

  terraform-apply-dev:
    needs: 
      - apply-dev-approval
    uses: ./.github/workflows/tf-apply.yml
    secrets: inherit
    with:
      environment: dev
